"""empty message

Revision ID: afee0f480e81
Revises: dac0da146ee4
Create Date: 2021-09-14 20:46:27.368078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afee0f480e81'
down_revision = 'dac0da146ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'name')
    # ### end Alembic commands ###
